name: MoneyPrinterPlugin
version: '${version}'
main: io.github.banditdevdk.moneyprinterplugin.MoneyPrinterPlugin
api-version: '1.20'
depend: [Vault]
author: BanditDevDK
description: Money printer plugin with customizable tiers and fuel system

commands:
  moneyprinter:
    description: Main money printer command
    usage: /moneyprinter <help|remove|give|list|reload|addfriend|removefriend|friends>
    aliases: [mp]

permissions:
  moneyprinter.use:
    description: Allows using money printers
    default: true
  moneyprinter.remove:
    description: Allows removing own printers
    default: true
  moneyprinter.admin:
    description: Admin commands and permissions
    default: op
  moneyprinter.tier.1:
    description: Access to tier 1 printers
    default: true
  moneyprinter.tier.2:
    description: Access to tier 2 printers
    default: true
  moneyprinter.tier.3:
    description: Access to tier 3 printers
    default: true
  moneyprinter.max.*:
    description: Permission-based max printer limits (e.g., moneyprinter.max.5)
    default: false